### ISSUE TITLE
Add imput fields for personal information

### ISSUE THREAD

**Issue by pA1nD** [penguin-academy/covid-19-py#41]
Allow personal information. Such as:
- Patient data: ID number, Birthdate and location
- Contact Data: Phone and name of the person filling the form

**Comment by aalvar76** [comment]
Hi, quick question. According the app flow, where should this information be requested?

**Comment by voluntadpear** [comment]
I'm concerned about a possible drawback that our recollection of personal data might have. See https://twitter.com/marsebu/status/1240256834000257025 and https://twitter.com/marsebu/status/1239178949768478720.

Since the current idea is to collect the data to our Firebase database, perhaps we should think how to ensure the correct usage of the data? An alternative could be to the client-side encryption using the Crypto API and let the end-users share a link with their encrypted data, like [Firefox Send](https://send.firefox.com/) does.

**Comment by pA1nD** [comment]
I added only the city and phone number. This is the bare minimum that allows us to generate useful data to actually draw a picture of the situation.

please check the update. It's added after the symptoms

**Comment by DARMA2020** [comment]
Se podría agregar una función de geolocalización a través de maps? Entonces se tiene localizado en tiempo Real a los pacientes y su entorno, también permitirá crear una cadena de transmisión en el tiempo y el espacio

**Comment by pA1nD** [comment]
@DARMA2020 we could but currently not doing this to keep it simple and make it more managable in the analysis as we have limited resources available right no.

**Comment by pA1nD** [comment]
closing this as it's implemented.
