### ISSUE TITLE
Add a question related to travel

### ISSUE THREAD

**Issue by camposcristianeze** [penguin-academy/covid-19-py#87]
I know it won't be a big majority of cases, but would be nice to include a question regarding travelling and dates, and in which airports there was a stopover. It might not happen but there's a petition to big companies to establish an opt-in [contact tracing](https://stop-covid.tech/)

**Comment by pA1nD** [comment]
we decided to not implement this as the WHO calls it a global epidemic. That implies that it's not contained in any country anymore and also our analysis are pointing to this fact that countries are rather "delayed in the impact" instead of "not affected".

That is why we do not have the question.

For tracing to have effect, I believe we would need something more powerful. I'd be very open to collaborate on a platform that reads the google location history that exists for everyone with an android device.

Reading this and crossing it with the one of COVID-19 patients would be a very interesting tool and i'd be happy to offer this in this website.

@camposcristianeze what do you think?

**Comment by camposcristianeze** [comment]
>we decided to not implement this as the WHO calls it a global epidemic. That implies that it's not contained in any country anymore and also our analysis are pointing to this fact that countries are rather "delayed in the impact" instead of "not affected".

Agreed that being covid-19 labelled as pandemic there won't be "not affected" 👍 

>For tracing to have effect, I believe we would need something more powerful. I'd be very open to collaborate on a platform that reads the google location history that exists for everyone with an android device.

I like this idea. Although Google won't be opening this as an API anytime soon, plus asking location data to the user sounds a bit creepy :). Although if it's opt-in and optional, y could help to have cleared data about areas with more potential of infection.
I found [this](https://stackoverflow.com/questions/17589718/future-of-google-location-history-api) and spent some time debugging and trying to understand the JSON from https://www.google.com/maps/timeline but it doesn't look like a straightforward approach...

On the other hand, cotrack from Argentina is discussing the implementation of something like [this](https://github.com/CoTrack-Social/app/issues/3) which could be helpful as well
![image](https://user-images.githubusercontent.com/1928706/77236720-ebe75580-6b9f-11ea-8c25-840a3c5c17c4.png)

**Comment by pA1nD** [comment]
That is interesting! Let's open a new issue for this and discuss it there also with others. #115 

Closing the travel question here.
